/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizeSvg(path: string, outPath: string): boolean
export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizeSvg(path: string, outPath: string): boolean
export function optimizeSvg(fileBuf: Buffer): Buffer
export function optimizeSvg(fileContent: string): string
export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizeSvg(path: string, outPath: string): boolean
export function optimizePng(path: string, outPath: string): Record<string, number>
export function optimizeSvg(path: string, outPath: string): boolean
export function pngCompress(path: string, outPath: string): Record<string, number>
export function svgCompress(path: string, outPath: string): boolean
